version: '3.8'

services:
  cache:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    container_name: redis-bullmq
  nestbull01:
    container_name: nest-bull-01
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    depends_on:
      - cache
    ports: 
      - 3000:3000
    restart: always
  nestbull02:
    container_name: nest-bull-02
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    depends_on:
      - cache
    ports: 
      - 3001:3000
    restart: always